---
- name: "Set uv variables"
  set_fact:
    uv_bin: "{{ ansible_env.HOME }}/.local/bin/uv"
    uv_tools:
      - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
      - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git' }
      - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
      - { name: 'bloodhound-ce', url: 'git+https://github.com/dirkjanm/BloodHound.py.git@bloodhound-ce' }

- name: "Ensure uv is installed"
  stat:
    path: "{{ uv_bin }}"
  register: uv_stat

- name: "Install the python tools via uv"
  shell: "{{ uv_bin }} tool install {{ item.url }}"
  args:
    executable: "/bin/bash"
    creates: "{{ ansible_env.HOME }}/.local/bin/{{ item.name }}"
  when: uv_stat.stat.exists
  loop: "{{ uv_tools }}"
  loop_control:
    label: "{{ item.name }}"
